Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2021-12, with the labels that each got.

#75 Main to live merge
  microsoft-community-training/analytics/custom-reports/database-schema.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
  microsoft-community-training/media/ManualAADSetup3.png
  microsoft-community-training/media/ManualAADSetup3a.PNG
  microsoft-community-training/media/Obtain clientsecret value.PNG
  microsoft-community-training/media/Redirect URIs.png
Labels: do-not-merge

#76 Added custom domain note to avoid CORS issue; Added steps to create Teams Manifest file
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/setup-custom-domain-url.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-teams-app-for-your-training-portal.md
Labels: do-not-merge, Change sent to author, azure/prod

#78 main
  microsoft-community-training/TOC.yml
  microsoft-community-training/frequently-asked-questions/generate-new-clientsecret-link-to-key-vault.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/setup-custom-domain-url.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-teams-app-for-your-training-portal.md
  microsoft-community-training/infrastructure-management/monitor-your-platform-infrastructure/troubleshoot-guide-for-azure-support.md
  microsoft-community-training/media/cs_addcs.png
  microsoft-community-training/media/cs_appconfigcs.png
  microsoft-community-training/media/cs_appreg.png
  microsoft-community-training/media/cs_cscheck.png
  microsoft-community-training/media/cs_kv.png
  microsoft-community-training/media/cs_kv_copy.png
  microsoft-community-training/media/cs_kv_create.png
  microsoft-community-training/media/cs_kv_new.png
  microsoft-community-training/media/cs_searchadb2c.png
  microsoft-community-training/settings/customize-the-certificate-template.md
Labels: do-not-merge

#80 Updated typo
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
Labels: do-not-merge, Change sent to author, azure/prod

#81 Live
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
Labels: qualifies-for-auto-merge, do-not-merge

#83 Multiauth doc changes
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-multiple-authentications-in-a-single-instance.md
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#82 Update configurations-on-the-training-platform.md
  microsoft-community-training/settings/configurations-on-the-training-platform.md
Labels: do-not-merge, Change sent to author, azure/prod

#84 live
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-multiple-authentications-in-a-single-instance.md
Labels: do-not-merge, Change sent to author, azure/prod

#85 Live
  microsoft-community-training/settings/configurations-on-the-training-platform.md
Labels: qualifies-for-auto-merge, do-not-merge
