Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2021-09, with the labels that each got.

#56 Offline learning doc
  microsoft-community-training/TOC.yml
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-teams-app-for-your-training-portal.md
  microsoft-community-training/learning-in-offline-mode/azure-IOT-edge-device-setup.md
  microsoft-community-training/learning-in-offline-mode/azure-IOT-hub-initial-setup.md
  microsoft-community-training/learning-in-offline-mode/offline-learning-with-microsoft-community-training.md
  microsoft-community-training/media/teamsapipermissions.png
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#58 Custom home page Doc
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/set-up-custom-homepage-for-your-mct-instance.md
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#59 Configuration: Link to external website
  microsoft-community-training/TOC.yml
  microsoft-community-training/settings/configurations-on-the-training-platform.md
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#61 Nidhi 1
  microsoft-community-training/infrastructure-management/monitor-your-platform-infrastructure/troubleshoot-guide-for-azure-support.md
  microsoft-community-training/media/MCT Architecture.png
Labels: do-not-merge

#62 add azure trouble shoot guide - 2
  microsoft-community-training/TOC.yml
Labels: needs-human-review, do-not-merge, review-team-triage

#64 warnings in live merge
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/Add-multiple-AAD-to-B2C-as-a-social-account.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
  microsoft-community-training/infrastructure-management/monitor-your-platform-infrastructure/troubleshoot-guide-for-azure-support.md
Labels: do-not-merge

#65 main to live merge
  microsoft-community-training/TOC.yml
  microsoft-community-training/analytics/custom-reports/database-schema.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/Add-multiple-AAD-to-B2C-as-a-social-account.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/set-up-custom-homepage-for-your-mct-instance.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-teams-app-for-your-training-portal.md
  microsoft-community-training/infrastructure-management/monitor-your-platform-infrastructure/troubleshoot-guide-for-azure-support.md
  microsoft-community-training/learning-in-offline-mode/azure-IOT-edge-device-setup.md
  microsoft-community-training/learning-in-offline-mode/azure-IOT-hub-initial-setup.md
  microsoft-community-training/learning-in-offline-mode/offline-learning-with-microsoft-community-training.md
  microsoft-community-training/media/LoginIdentity1.png
  microsoft-community-training/media/LoginIdentity10.png
  microsoft-community-training/media/LoginIdentity11.png
  microsoft-community-training/media/LoginIdentity12.png
  microsoft-community-training/media/LoginIdentity13.png
  microsoft-community-training/media/LoginIdentity14.png
  microsoft-community-training/media/LoginIdentity2.png
  microsoft-community-training/media/LoginIdentity3.png
  microsoft-community-training/media/LoginIdentity4.png
  microsoft-community-training/media/LoginIdentity5.png
  microsoft-community-training/media/LoginIdentity6.png
  microsoft-community-training/media/LoginIdentity7.png
  microsoft-community-training/media/LoginIdentity8.png
  microsoft-community-training/media/LoginIdentity9.png
  microsoft-community-training/media/MCT Architecture.png
  microsoft-community-training/media/MultipleAAD1.png
  microsoft-community-training/media/MultipleAAD2.png
  microsoft-community-training/media/teamsapipermissions.png
  microsoft-community-training/settings/configurations-on-the-training-platform.md
Labels: do-not-merge
