Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2022-10, with the labels that each got.

#204 Bulk Metadata Update - ms.topic update.
  microsoft-community-training/analytics/custom-reports/power-bi-integration.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, power-bi-embedded/svc

#205 sai_mct to main
  microsoft-community-training/TOC.yml
  microsoft-community-training/content-management/create-content/create-course-category/create-a-category.md
  microsoft-community-training/content-management/create-content/create-learning-path/create-a-learning-path.md
  microsoft-community-training/content-management/manage-content/manage-course-category/change-category-details.md
  microsoft-community-training/content-management/manage-content/manage-learning-path/change-learning-path-details.md
  microsoft-community-training/frequently-asked-questions/custom-integration.md
  microsoft-community-training/media/Categorylocalizationcreate.png
  microsoft-community-training/media/Categorylocedit.png
  microsoft-community-training/media/Categoryloceditaddlang.png
  microsoft-community-training/media/LPloccreate.png
  microsoft-community-training/media/LPloccreateadd.png
  microsoft-community-training/media/LPlocedit.png
  microsoft-community-training/media/Orgbrandedit.png
  microsoft-community-training/media/Orgbrandsettings.png
  microsoft-community-training/media/assocfiled.png
  microsoft-community-training/media/choosedep.png
  microsoft-community-training/media/depassocaddoption.png
  microsoft-community-training/media/depassocupload.png
  microsoft-community-training/media/depchooseoptions.png
  microsoft-community-training/media/manageorg.png
  microsoft-community-training/media/maskfields.png
  microsoft-community-training/media/maskingfields.png
  microsoft-community-training/settings/add-additional-profile-fields-for-user-information.md
  microsoft-community-training/settings/configurations-on-the-training-platform.md
  microsoft-community-training/user-management/organization-management.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-august-2022.md
Labels: do-not-merge

#206 [BrokenLinks] fix breadcrumb path
  microsoft-community-training/docfx.json
Labels: needs-human-review, do-not-merge
