Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2022-04, with the labels that each got.

#122 Add PWA feature in Configurations page
  microsoft-community-training/settings/configurations-on-the-training-platform.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#121 [BrokenLinksH2] fixing broken link
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/customize-the-name-and-icon-of-the-training-tab-in-ms-teams.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#123 Main to Live merge sync
  microsoft-community-training/content-management/create-content/create-course-category/upload-content-to-a-course.md
  microsoft-community-training/frequently-asked-questions/faqs-course.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/customize-the-name-and-icon-of-the-training-tab-in-ms-teams.md
  microsoft-community-training/settings/configurations-on-the-training-platform.md
Labels: do-not-merge, Change sent to author, azure/prod

#132 [BrokenLinksH2] Fixed the link path
  microsoft-community-training/rest-api-management/api-documentation.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#131 [BrokenLinksH2] Fixed the link path
  microsoft-community-training/learning-in-offline-mode/azure-IOT-edge-device-setup.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#130 [BrokenLinksH2] Fixed the link path
  microsoft-community-training/infrastructure-management/install-your-platform-instance/setup-platform-instance-on-azure-subscription-for-nonprofits.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#129 [BrokenLinksH2] Fixed the link path
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#128 [BrokenLinksH2] Fixed the link path
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/customize-the-name-and-icon-of-the-training-tab-in-ms-teams.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#127 [BrokenLinksH2] Fixed the link path
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/Add-multiple-AAD-to-B2C-as-a-social-account.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#126 [BrokenLinksH2] Fixed the link path
  microsoft-community-training/frequently-asked-questions/faqs-general.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#125 [BrokenLinksH2] Fixed the link path
  microsoft-community-training/frequently-asked-questions/faqs-course.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#133 April 2022 changes check-in
  microsoft-community-training/TOC.yml
  microsoft-community-training/analytics/custom-reports/database-schema.md
  microsoft-community-training/content-management/create-content/create-course-category/create-a-new-course.md
  microsoft-community-training/learner-experience/pwa-app.md
  microsoft-community-training/media/marketplacesearch.png
  microsoft-community-training/media/pwaoffdelete.png
  microsoft-community-training/media/pwaoffdownload.png
  microsoft-community-training/media/pwaoffhomepage.png
  microsoft-community-training/media/pwaofflang.png
  microsoft-community-training/media/pwaofflogin.png
  microsoft-community-training/media/pwaoffvoureview.png
Labels: needs-human-review, do-not-merge

#134 sync main
  microsoft-community-training/frequently-asked-questions/faqs-course.md
  microsoft-community-training/frequently-asked-questions/faqs-general.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/Add-multiple-AAD-to-B2C-as-a-social-account.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/customize-the-name-and-icon-of-the-training-tab-in-ms-teams.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/setup-platform-instance-on-azure-subscription-for-nonprofits.md
  microsoft-community-training/learning-in-offline-mode/azure-IOT-edge-device-setup.md
  microsoft-community-training/rest-api-management/api-documentation.md
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#135 New upload format and new question firmats
  microsoft-community-training/content-management/create-content/create-course-category/add-assessments-to-a-course.md
  microsoft-community-training/content-management/create-content/create-course-category/upload-content-to-a-course.md
  microsoft-community-training/media/Assessment - FillBlank Learner.PNG
  microsoft-community-training/media/Assessment - FillBlank.PNG
  microsoft-community-training/media/Assessment - TrueFalse Learner.PNG
  microsoft-community-training/media/Assessment - TrueFalse.PNG
  microsoft-community-training/media/Assessment - multi-correct Learner.PNG
  microsoft-community-training/media/Assessment - multi-correct detailed.PNG
  microsoft-community-training/media/Assessment - question type.PNG
  microsoft-community-training/media/New Lesson SCORM.PNG
  microsoft-community-training/media/New Lesson replace file.PNG
  microsoft-community-training/media/New Lesson v2.PNG
Labels: do-not-merge, Change sent to author, azure/prod

#136 Minor corrections in assesments doc
  microsoft-community-training/content-management/create-content/create-course-category/add-assessments-to-a-course.md
  microsoft-community-training/media/Assessment - csv sample upload v2.PNG
  microsoft-community-training/media/Assessment - csv upload.PNG
  microsoft-community-training/media/Assessment - graded question.PNG
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#140 Samarth
  microsoft-community-training/content-management/create-content/create-course-category/add-assessments-to-a-course.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#141 Sai mct
  microsoft-community-training/frequently-asked-questions/faqs-course.md
  microsoft-community-training/media/SCORMupload.png
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#142 SCORM update
  microsoft-community-training/content-management/create-content/create-course-category/upload-content-to-a-course.md
  microsoft-community-training/frequently-asked-questions/faqs-course.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#137 Org Admin and global content
  microsoft-community-training/content-management/content-management-overview.md
  microsoft-community-training/content-management/create-content/create-course-category/create-a-category.md
  microsoft-community-training/content-management/create-content/create-learning-path/create-a-learning-path.md
  microsoft-community-training/frequently-asked-questions/faqs-course.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-teams-app-for-your-training-portal.md
  microsoft-community-training/media/Add Admin by Org Admin 2.png
  microsoft-community-training/media/Add Admin by Org Admin 3.png
  microsoft-community-training/media/Add Admin by Org Admin.png
  microsoft-community-training/media/Add Organization in MultiTenant.png
  microsoft-community-training/media/Add Organization2 Multi Tenant.png
  microsoft-community-training/media/Add tenant ID Organization.png
  microsoft-community-training/media/Dowload PDF feature.png
  microsoft-community-training/media/Enable PDF Download.png
  microsoft-community-training/media/Global Content Configuration.png
  microsoft-community-training/media/Org Admin addition.png
  microsoft-community-training/settings/configurations-on-the-training-platform.md
  microsoft-community-training/user-management/add-users/add-an-administrator-to-the-portal.md
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#143 final changes
  microsoft-community-training/content-management/content-management-overview.md
  microsoft-community-training/media/Enable PDF Download3.png
  microsoft-community-training/settings/configurations-on-the-training-platform.md
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#148 changes sync
  microsoft-community-training/TOC.yml
  microsoft-community-training/content-management/create-content/create-course-category/upload-content-to-a-course.md
  microsoft-community-training/media/Enable PDF Download learner view v2.PNG
  microsoft-community-training/media/Enable PDF Download learner view.png
  microsoft-community-training/media/Full screen lesson.png
  microsoft-community-training/media/Search Content Marketplace.png
  microsoft-community-training/media/Separate page for certificates.png
  microsoft-community-training/media/Upload SCORM.png
  microsoft-community-training/settings/configurations-on-the-training-platform.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-may-2022.md
Labels: do-not-merge, Change sent to author, azure/prod

#149 PWA options
  microsoft-community-training/learner-experience/pwa-app.md
Labels: qualifies-for-auto-merge, do-not-merge

#151 changes to whats new
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-may-2022.md
Labels: do-not-merge, Change sent to author, azure/prod
