Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2022-05, with the labels that each got.

#152 changes after review
  microsoft-community-training/content-management/content-management-overview.md
  microsoft-community-training/content-management/create-content/create-course-category/create-a-category.md
  microsoft-community-training/content-management/create-content/create-learning-path/create-a-learning-path.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-teams-app-for-your-training-portal.md
  microsoft-community-training/media/After Common Content Enabled.png
  microsoft-community-training/media/Commin in MultiTenant.png
  microsoft-community-training/user-management/organization-management.md
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#153 Link updates
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-may-2022.md
Labels: do-not-merge, Change sent to author, azure/prod

#154 content endpoint change
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/setup-custom-domain-url.md
  microsoft-community-training/media/custom domain endpoint setting.png
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#157 Live sync May
  microsoft-community-training/analytics/custom-reports/database-schema.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-may-2022.md
Labels: do-not-merge, Change sent to author, azure/prod

#159 storage limit edit PWA
  microsoft-community-training/learner-experience/pwa-app.md
Labels: do-not-merge

#161 Update pwa-app.md
  microsoft-community-training/learner-experience/pwa-app.md
Labels: qualifies-for-auto-merge, do-not-merge
