Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2022-07, with the labels that each got.

#165 Live
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-may-2022.md
Labels: do-not-merge, Change sent to author, azure/prod

#166 Live
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-publish-mobile-app.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#167 [BrokenLinks] add hierarchy to contextual navigation
  microsoft-community-training/breadcrumb/toc.yml
Labels: needs-human-review, do-not-merge, review-team-triage

#168 Changes to Org management and May'22 doc
  microsoft-community-training/media/Allusersorg.png
  microsoft-community-training/media/bulkuserorg.png
  microsoft-community-training/media/filterorg.png
  microsoft-community-training/media/orgcontactadd.png
  microsoft-community-training/user-management/organization-management.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-may-2022.md
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#169 Main to Live sync - Jul22
  microsoft-community-training/breadcrumb/toc.yml
  microsoft-community-training/media/Allusersorg.png
  microsoft-community-training/media/bulkuserorg.png
  microsoft-community-training/media/filterorg.png
  microsoft-community-training/media/orgcontactadd.png
  microsoft-community-training/user-management/organization-management.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-may-2022.md
Labels: do-not-merge
