Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2022-02, with the labels that each got.

#93 MultiTenant Teams SSO
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-teams-app-for-your-training-portal.md
  microsoft-community-training/media/Teams SSO MultiTenant 1.png
  microsoft-community-training/media/Teams SSO MultiTenant 2.png
  microsoft-community-training/media/Teams SSO MultiTenant 3.png
  microsoft-community-training/media/Teams SSO MultiTenant 4.png
  microsoft-community-training/media/Teams SSO MultiTenant 5.png
  microsoft-community-training/media/Teams SSO MultiTenant 6.png
  microsoft-community-training/media/Teams SSO MultiTenant 7.png
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#94 Modified changes in Assessment and learner view
  microsoft-community-training/TOC.yml
  microsoft-community-training/content-management/content-management-overview.md
  microsoft-community-training/content-management/create-content/create-course-category/add-assessments-to-a-course.md
  microsoft-community-training/content-management/create-content/create-course-category/create-a-new-course.md
  microsoft-community-training/content-management/create-content/create-course-category/upload-content-to-a-course.md
  microsoft-community-training/frequently-asked-questions/faqs-course.md
  microsoft-community-training/get-started/step-by-step-configuration-guide.md
  microsoft-community-training/learner-experience/web-app.md
  microsoft-community-training/media/Assessment - New AssessmentQuiz.PNG
  microsoft-community-training/media/Assessment - answer explanantion.PNG
  microsoft-community-training/media/Assessment - multi-correct detailed.PNG
  microsoft-community-training/media/Profile Field - edit from learner view 1.PNG
  microsoft-community-training/media/Profile Field - edit from learner view 2.PNG
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-april-2020.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-february-2020.md
Labels: do-not-merge, Change sent to author, azure/prod

#95 pic change in Teams SSO
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-teams-app-for-your-training-portal.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#96 image allignment corrected
  microsoft-community-training/content-management/create-content/create-course-category/add-assessments-to-a-course.md
Labels: do-not-merge, Change sent to author, azure/prod

#97 Added learner profile field search
  microsoft-community-training/learner-experience/web-app.md
  microsoft-community-training/media/Profile Field - edit from learner view 2.PNG
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#98 Sai mct
  microsoft-community-training/TOC.yml
  microsoft-community-training/content-management/create-content/create-course-category/content-marketplace.md
  microsoft-community-training/content-management/create-content/create-course-category/create-a-new-course.md
  microsoft-community-training/media/assesmentsfeb22.png
  microsoft-community-training/media/assessment-newold.png
  microsoft-community-training/media/groupsearch.png
  microsoft-community-training/media/marketplacewatsnew.png
  microsoft-community-training/media/searchinpf.png
  microsoft-community-training/media/watsnewpf.png
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-february-2022.md
  microsoft-community-training/whats-new-in-microsoft-community-training/whats-new-in-microsoft-community-training.md
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#99 Sai mct
  microsoft-community-training/content-management/create-content/create-course-category/add-assessments-to-a-course.md
  microsoft-community-training/learner-experience/web-app.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-february-2022.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#100 Sai mct
  microsoft-community-training/frequently-asked-questions/faqs-course.md
  microsoft-community-training/media/viemoshare.png
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#103 File upload script PWA
  microsoft-community-training/media/SingleFileUpload.ps1
Labels: do-not-merge
