Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2022-01, with the labels that each got.

#86 Update configure-the-look-and-feel-of-your-portal.md
  microsoft-community-training/settings/configure-the-look-and-feel-of-your-portal.md
Labels: do-not-merge, Change sent to author, azure/prod

#87 Update faqs-general.md
  microsoft-community-training/frequently-asked-questions/faqs-general.md
Labels: do-not-merge, Change sent to author, azure/prod

#88 Live
  microsoft-community-training/frequently-asked-questions/faqs-general.md
  microsoft-community-training/settings/configure-the-look-and-feel-of-your-portal.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#89 Assessment and profile field changes
  microsoft-community-training/content-management/create-content/create-course-category/add-practice-quizzes-and-exam.md
  microsoft-community-training/media/Additional Profil Field - Main screen.PNG
  microsoft-community-training/media/Assessment - New Assessment.PNG
  microsoft-community-training/media/Assessment - New AssessmentFinalExam.PNG
  microsoft-community-training/media/Assessment - New AssessmentQuiz.PNG
  microsoft-community-training/media/Assessment - answer explanantion.PNG
  microsoft-community-training/media/Assessment - answer explanantionlogo.PNG
  microsoft-community-training/media/Assessment - csv sample upload.PNG
  microsoft-community-training/media/Assessment - graded question.PNG
  microsoft-community-training/media/Assessment - multi-correct.PNG
  microsoft-community-training/media/Assessment - non-graded question.PNG
  microsoft-community-training/media/Profile Field - add translation.PNG
  microsoft-community-training/media/Profile Field - download-upload list.PNG
  microsoft-community-training/media/Profile Field - error message and description.PNG
  microsoft-community-training/media/Profile Field - name translation.PNG
  microsoft-community-training/media/Profile Field - save translation.PNG
  microsoft-community-training/media/Profile Field - set validation.PNG
  microsoft-community-training/settings/add-additional-profile-fields-for-user-information.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-april-2020.md
Labels: do-not-merge, Change sent to author, azure/prod

#90 Content Marketplace
  microsoft-community-training/content-management/create-content/create-course-category/create-a-category.md
  microsoft-community-training/content-management/create-content/create-course-category/create-a-new-course.md
  microsoft-community-training/content-management/manage-content/manage-course-category/move-course-content-across-training-instance.md
  microsoft-community-training/frequently-asked-questions/faqs-general.md
  microsoft-community-training/frequently-asked-questions/faqs-user-management.md
  microsoft-community-training/get-started/step-by-step-configuration-guide.md
  microsoft-community-training/learner-experience/web-app.md
  microsoft-community-training/media/marketplace1.png
  microsoft-community-training/media/marketplaceall.png
  microsoft-community-training/media/marketplaceimg2.png
  microsoft-community-training/media/marketplaceimg3.png
  microsoft-community-training/media/marketplaceimg4.png
  microsoft-community-training/media/marketplaceimg5.png
  microsoft-community-training/rest-api-management/service-to-service-authentication.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2021/what-new-in-july-2021.md
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#91 Sai mct
  microsoft-community-training/rest-api-management/service-to-service-authentication.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#92 Added note in custom domain
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/setup-custom-domain-url.md
Labels: do-not-merge, Change sent to author, azure/prod
