Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2022-09, with the labels that each got.

#190 Bulk Metadata Update - Remove ms.service Value
  microsoft-community-training/analytics/custom-reports/power-bi-integration.md
  microsoft-community-training/index.yml
Labels: do-not-merge

#191 [BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute
  microsoft-community-training/frequently-asked-questions/faqs-general.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/set-up-custom-homepage-for-your-mct-instance.md
Labels: do-not-merge, Change sent to author, learning-azure/prod

#192 disable auto enroll course
  microsoft-community-training/media/featuredisableautoenrollcourse.png
  microsoft-community-training/settings/configurations-on-the-training-platform.md
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod

#193 Main to Live Sync
  microsoft-community-training/analytics/custom-reports/power-bi-integration.md
  microsoft-community-training/frequently-asked-questions/faqs-general.md
  microsoft-community-training/frequently-asked-questions/faqs-user-management.md
  microsoft-community-training/index.yml
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/set-up-custom-homepage-for-your-mct-instance.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
  microsoft-community-training/media/Steps to retrieve learner certificates for a course.docx
  microsoft-community-training/media/Steps to retrieve learner certificates for a course_LP.docx
  microsoft-community-training/media/featuredisableautoenrollcourse.png
  microsoft-community-training/settings/configurations-on-the-training-platform.md
Labels: do-not-merge, Change sent to author, learning-azure/prod, power-bi-embedded/svc

#195 adjustment pdf
  microsoft-community-training/settings/configurations-on-the-training-platform.md
Labels: do-not-merge, Change sent to author, learning-azure/prod

#196 Correction screen shot
  microsoft-community-training/settings/configurations-on-the-training-platform.md
Labels: do-not-merge

#198 Main to Line
  microsoft-community-training/frequently-asked-questions/custom-integration.md
  microsoft-community-training/frequently-asked-questions/web-mobile-app.md
Labels: do-not-merge, Change sent to author, learning-azure/prod

#201 [BULK UPDATE] DocuTune - Rebranding
  microsoft-community-training/content-management/create-content/create-course-category/content-marketplace.md
  microsoft-community-training/frequently-asked-questions/faqs-course.md
  microsoft-community-training/frequently-asked-questions/faqs-general.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-april-2020.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, learning-azure/prod

#200 [BULK UPDATE] DocuTune - Rebranding links
  microsoft-community-training/frequently-asked-questions/faqs-user-management.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-multiple-authentications-in-a-single-instance.md
  microsoft-community-training/infrastructure-management/monitor-your-platform-infrastructure/troubleshoot-guide-for-azure-support.md
  microsoft-community-training/settings/configurations-on-the-training-platform.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-february-2020.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, learning-azure/prod
