Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2022-08, with the labels that each got.

#171 main merge Aug release 2022
  microsoft-community-training/analytics/custom-reports/database-schema.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
  microsoft-community-training/infrastructure-management/monitor-your-platform-infrastructure/troubleshoot-guide-for-azure-support.md
  microsoft-community-training/learner-experience/pwa-app.md
  microsoft-community-training/media/cliendIDB2C.png
  microsoft-community-training/media/cliendsecretB2C.png
  microsoft-community-training/user-management/organization-management.md
Labels: needs-human-review, do-not-merge

#172 Features:disableProfileEditForNonSuperAdmin
  microsoft-community-training/settings/configurations-on-the-training-platform.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#173 FAQ update
  microsoft-community-training/frequently-asked-questions/faqs-general.md
  microsoft-community-training/rest-api-management/api-documentation.md
Labels: do-not-merge, Change sent to author, azure/prod

#176 webview of mct
  microsoft-community-training/frequently-asked-questions/custom-integration.md
  microsoft-community-training/rest-api-management/api-documentation.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#177 Main to Live sync Aug22
  microsoft-community-training/analytics/custom-reports/database-schema.md
  microsoft-community-training/frequently-asked-questions/custom-integration.md
  microsoft-community-training/frequently-asked-questions/faqs-general.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-teams-app-for-your-training-portal.md
  microsoft-community-training/infrastructure-management/monitor-your-platform-infrastructure/troubleshoot-guide-for-azure-support.md
  microsoft-community-training/learner-experience/pwa-app.md
  microsoft-community-training/media/cliendIDB2C.png
  microsoft-community-training/media/cliendsecretB2C.png
  microsoft-community-training/rest-api-management/api-documentation.md
  microsoft-community-training/settings/configurations-on-the-training-platform.md
  microsoft-community-training/user-management/organization-management.md
Labels: do-not-merge

#182 Bulk Metadata Update: ms.prod updates.
  microsoft-community-training/analytics/custom-reports/database-schema.md
  microsoft-community-training/content-management/content-management-overview.md
  microsoft-community-training/content-management/create-content/create-course-category/add-assessments-to-a-course.md
  microsoft-community-training/content-management/create-content/create-course-category/create-a-category.md
  microsoft-community-training/frequently-asked-questions/faqs-general.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/customize-the-name-and-icon-of-the-training-tab-in-ms-teams.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-publish-mobile-app.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/setup-platform-instance-on-azure-subscription-for-nonprofits.md
  microsoft-community-training/learner-experience/pwa-app.md
  microsoft-community-training/learning-in-offline-mode/azure-IOT-edge-device-setup.md
  microsoft-community-training/settings/add-additional-profile-fields-for-user-information.md
  microsoft-community-training/settings/configurations-on-the-training-platform.md
  microsoft-community-training/user-management/add-users/add-an-administrator-to-the-portal.md
  microsoft-community-training/user-management/organization-management.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-may-2022.md
Labels: do-not-merge, Change sent to author, learning-azure/prod

#181 Bulk Metadata Update - Remove/Replace ms.product value
  microsoft-community-training/content-management/create-content/create-course-category/content-marketplace.md
  microsoft-community-training/content-management/create-content/create-course-category/create-a-new-course.md
  microsoft-community-training/content-management/create-content/create-course-category/upload-content-to-a-course.md
  microsoft-community-training/content-management/create-content/create-learning-path/create-a-learning-path.md
  microsoft-community-training/content-management/manage-content/manage-course-category/move-course-content-across-training-instance.md
  microsoft-community-training/frequently-asked-questions/custom-integration.md
  microsoft-community-training/frequently-asked-questions/faqs-course.md
  microsoft-community-training/frequently-asked-questions/faqs-user-management.md
  microsoft-community-training/frequently-asked-questions/generate-new-clientsecret-link-to-key-vault.md
  microsoft-community-training/get-started/step-by-step-configuration-guide.md
  microsoft-community-training/get-started/user-role-and-management-portal-overview.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/Add-multiple-AAD-to-B2C-as-a-social-account.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/learner-action-events-infrastructure.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/setup-custom-domain-url.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-multiple-authentications-in-a-single-instance.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-teams-app-for-your-training-portal.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/installation-guide-detailed-steps.md
  microsoft-community-training/infrastructure-management/monitor-your-platform-infrastructure/troubleshoot-guide-for-azure-support.md
  microsoft-community-training/learner-experience/web-app.md
  microsoft-community-training/rest-api-management/api-documentation.md
  microsoft-community-training/rest-api-management/service-to-service-authentication.md
  microsoft-community-training/settings/configure-the-look-and-feel-of-your-portal.md
  microsoft-community-training/settings/customize-languages-for-the-learners-on-the-platform.md
  microsoft-community-training/settings/customize-the-certificate-template.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-april-2020.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-february-2020.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2021/what-new-in-july-2021.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2021/whats-new-in-october-2021.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-february-2022.md
  microsoft-community-training/whats-new-in-microsoft-community-training/whats-new-in-microsoft-community-training.md
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod

#180 Bulk Metadata Update: ms.prod updates.
  microsoft-community-training/analytics/analytics-overview.md
  microsoft-community-training/analytics/in-built-reports/category-view-report.md
  microsoft-community-training/content-management/create-content/create-learning-path/add-course-to-a-learning-path.md
  microsoft-community-training/content-management/manage-content/manage-course-category/change-course-details.md
  microsoft-community-training/frequently-asked-questions/analytics-reporting.md
  microsoft-community-training/frequently-asked-questions/faqs-installation-and-setup.md
  microsoft-community-training/frequently-asked-questions/portal-branding-customization.md
  microsoft-community-training/frequently-asked-questions/pricing-subscription.md
  microsoft-community-training/frequently-asked-questions/security-and-privacy.md
  microsoft-community-training/frequently-asked-questions/web-mobile-app.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/azure-front-door-migration.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/business-continuity-and-disaster-recovery-for-your-platform-instance.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/set-up-custom-homepage-for-your-mct-instance.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/apis.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/troubleshooting.md
  microsoft-community-training/infrastructure-management/monitor-your-platform-infrastructure/backup-and-recovery.md
  microsoft-community-training/infrastructure-management/monitor-your-platform-infrastructure/monitor-your-infrastructure.md
  microsoft-community-training/learning-in-offline-mode/azure-IOT-hub-initial-setup.md
  microsoft-community-training/learning-in-offline-mode/offline-learning-with-microsoft-community-training.md
  microsoft-community-training/settings/enable-course-level-certificate.md
  microsoft-community-training/settings/restrict-content-access-to-group-administrators.md
  microsoft-community-training/user-management/manage-users/De-assigning-content-from-user.md
  microsoft-community-training/user-management/manage-users/assign-content-to-group-users.md
  microsoft-community-training/user-management/manage-users/edit-user-profile-on-the-platform.md
  microsoft-community-training/user-management/manage-users/remove-user-from-group.md
  microsoft-community-training/user-management/organize-users/add-multiple-users-to-the-group.md
  microsoft-community-training/user-management/organize-users/setup-automatic-user-enrollment-for-a-group-1.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-august-2020.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-june-2020.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2021/what-new-in-march-2021.md
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod

#179 Bulk Metadata Update: ms.prod updates
  microsoft-community-training/analytics/in-built-reports/course-view-report.md
  microsoft-community-training/analytics/in-built-reports/group-view-report.md
  microsoft-community-training/analytics/in-built-reports/learner-report-card-view.md
  microsoft-community-training/analytics/in-built-reports/overall-summary.md
  microsoft-community-training/content-management/create-content/create-course-category/add-feedback-form-for-a-course.md
  microsoft-community-training/content-management/create-content/create-course-category/add-subtitles-or-captions-to-video-content.md
  microsoft-community-training/content-management/create-content/create-course-category/publishing-course.md
  microsoft-community-training/content-management/create-content/create-learning-path/publish-a-learning-path-on-the-portal.md
  microsoft-community-training/content-management/manage-content/manage-course-category/add-an-administrator-for-a-course.md
  microsoft-community-training/content-management/manage-content/manage-course-category/change-category-details.md
  microsoft-community-training/content-management/manage-content/manage-course-category/manage-users-for-a-course.md
  microsoft-community-training/content-management/manage-content/manage-learning-path/add-an-administrator-for-a-learning-path.md
  microsoft-community-training/content-management/manage-content/manage-learning-path/change-learning-path-details.md
  microsoft-community-training/content-management/manage-content/manage-learning-path/manage-user-for-a-learning-path.md
  microsoft-community-training/frequently-asked-questions/user-roles-groups.md
  microsoft-community-training/get-started/microsoft-community-training-overview.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/delete-your-training-instance.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/scale-up-instance-configuration.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/installation-overview.md
  microsoft-community-training/learner-experience/mobile.md
  microsoft-community-training/settings/link-to-external-website-on-learner-Homepage.md
  microsoft-community-training/settings/request-a-new-language.md
  microsoft-community-training/settings/restrict-portal-access-to-users-outside-your-organization.md
  microsoft-community-training/user-management/add-users/add-users-to-the-portal-1.md
  microsoft-community-training/user-management/manage-users/remove-user-from-the-portal.md
  microsoft-community-training/user-management/manage-users/send-announcement-to-the-users.md
  microsoft-community-training/user-management/organize-users/add-a-single-user-to-the-group.md
  microsoft-community-training/user-management/organize-users/create-a-new-group.md
  microsoft-community-training/user-management/user-management-overview.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-december-2020.md
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod

#183 Main merge
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-publish-mobile-app.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, learning-azure/prod

#184 PWA faq updates
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-publish-mobile-app.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, learning-azure/prod

#187 Azure AD register an App URL
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, learning-azure/prod

#188 Update create-publish-mobile-app.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-publish-mobile-app.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, learning-azure/prod

#189 Native phone login ADB2C
  microsoft-community-training/frequently-asked-questions/faqs-user-management.md
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod
