Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2022-03, with the labels that each got.

#105 Update customize-the-certificate-template.md
  microsoft-community-training/settings/customize-the-certificate-template.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#106 Sai mct
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-publish-mobile-app.md
  microsoft-community-training/media/PWA_migration.png
  microsoft-community-training/settings/customize-the-certificate-template.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-february-2022.md
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#107 PWA changes
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-publish-mobile-app.md
  microsoft-community-training/media/PWA_migration.png
  microsoft-community-training/settings/customize-the-certificate-template.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-february-2022.md
Labels: do-not-merge

#109 Courselist for MS digital content
  microsoft-community-training/content-management/create-content/create-course-category/content-marketplace.md
Labels: do-not-merge, Change sent to author, azure/prod

#111 Live
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
  microsoft-community-training/media/aad_app_creation.ps1
Labels: needs-human-review, do-not-merge, Change sent to author, azure/prod

#113 Live
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-february-2022.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#114 Update custom-integration.md
  microsoft-community-training/frequently-asked-questions/custom-integration.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#115 36 changes behind updated
  microsoft-community-training/TOC.yml
  microsoft-community-training/content-management/create-content/create-course-category/add-assessments-to-a-course.md
  microsoft-community-training/content-management/create-content/create-course-category/content-marketplace.md
  microsoft-community-training/content-management/create-content/create-course-category/create-a-new-course.md
  microsoft-community-training/frequently-asked-questions/faqs-course.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-login-social-work-school-account.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-publish-mobile-app.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-teams-app-for-your-training-portal.md
  microsoft-community-training/learner-experience/web-app.md
  microsoft-community-training/media/PWA_migration.png
  microsoft-community-training/media/SingleFileUpload.ps1
  microsoft-community-training/media/aad_app_creation.ps1
  microsoft-community-training/media/assesmentsfeb22.png
  microsoft-community-training/media/assessment-newold.png
  microsoft-community-training/media/groupsearch.png
  microsoft-community-training/media/marketplacewatsnew.png
  microsoft-community-training/media/searchinpf.png
  microsoft-community-training/media/viemoshare.png
  microsoft-community-training/media/watsnewpf.png
  microsoft-community-training/settings/customize-the-certificate-template.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-february-2022.md
  microsoft-community-training/whats-new-in-microsoft-community-training/whats-new-in-microsoft-community-training.md
Labels: needs-human-review, do-not-merge

#116 Live
  microsoft-community-training/settings/add-additional-profile-fields-for-user-information.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-february-2022.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, azure/prod

#118 Samarth
  microsoft-community-training/content-management/create-content/create-course-category/upload-content-to-a-course.md
  microsoft-community-training/frequently-asked-questions/faqs-course.md
Labels: do-not-merge, Change sent to author, azure/prod

#119 Asthetic improvements
  microsoft-community-training/frequently-asked-questions/faqs-course.md
Labels: do-not-merge, Change sent to author, azure/prod
