Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2023-10, with the labels that each got.

#283 Language and extra note added
  microsoft-community-training/frequently-asked-questions/faqs-installation-and-setup.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/Setup-Azure-ADB2C-Native-Phone-Authentication.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/installation-guide-detailed-steps.md
  microsoft-community-training/media/B2C_ph_mig.ps1
  microsoft-community-training/media/Phone_Email_Base.xml
  microsoft-community-training/media/SignUpOrSignInWithPhone.xml
  microsoft-community-training/settings/request-a-new-language.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-august-2020.md
Labels: do-not-merge

#289 Updated text for Get-started section.
  microsoft-community-training/get-started/microsoft-community-training-overview.md
  microsoft-community-training/get-started/step-by-step-configuration-guide.md
  microsoft-community-training/get-started/user-role-and-management-portal-overview.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2021/what-new-in-march-2021.md
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod

#290 updated text for learner-experience section
  microsoft-community-training/learner-experience/mobile.md
  microsoft-community-training/learner-experience/pwa-app.md
  microsoft-community-training/learner-experience/web-app.md
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod

#293 Learning in offline mode
  microsoft-community-training/learning-in-offline-mode/azure-IOT-edge-device-setup.md
  microsoft-community-training/learning-in-offline-mode/azure-IOT-hub-initial-setup.md
  microsoft-community-training/learning-in-offline-mode/frequently-asked-questions.md
  microsoft-community-training/learning-in-offline-mode/offline-learning-with-microsoft-community-training.md
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod

#292 Frequently asked questions
  microsoft-community-training/frequently-asked-questions/analytics-reporting.md
  microsoft-community-training/frequently-asked-questions/custom-integration.md
  microsoft-community-training/frequently-asked-questions/faqs-course.md
  microsoft-community-training/frequently-asked-questions/faqs-general.md
  microsoft-community-training/frequently-asked-questions/faqs-installation-and-setup.md
  microsoft-community-training/frequently-asked-questions/faqs-user-management.md
  microsoft-community-training/frequently-asked-questions/generate-new-clientsecret-link-to-key-vault.md
  microsoft-community-training/frequently-asked-questions/portal-branding-customization.md
  microsoft-community-training/frequently-asked-questions/pricing-subscription.md
  microsoft-community-training/frequently-asked-questions/security-and-privacy.md
  microsoft-community-training/frequently-asked-questions/user-roles-groups.md
  microsoft-community-training/frequently-asked-questions/web-mobile-app.md
Labels: do-not-merge, Change sent to author, learning-azure/prod

#291 rest-api-management [text-updated]
  microsoft-community-training/rest-api-management/api-documentation.md
  microsoft-community-training/rest-api-management/service-to-service-authentication.md
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod

#296 Reliability: Adding breadcrumb and link to reliability
  microsoft-community-training/TOC.yml
  microsoft-community-training/breadcrumb/toc.yml
Labels: needs-human-review, do-not-merge, Change sent to author

#299 user-management text updated
  microsoft-community-training/user-management/add-users/add-an-administrator-to-the-portal.md
  microsoft-community-training/user-management/add-users/add-users-to-the-portal-1.md
  microsoft-community-training/user-management/manage-users/De-assigning-content-from-user.md
  microsoft-community-training/user-management/manage-users/assign-content-to-group-users.md
  microsoft-community-training/user-management/manage-users/delete-user-from-group.md
  microsoft-community-training/user-management/manage-users/delete-user-from-the-platform.md
  microsoft-community-training/user-management/manage-users/edit-user-profile-on-the-platform.md
  microsoft-community-training/user-management/manage-users/remove-user-from-group.md
  microsoft-community-training/user-management/manage-users/remove-user-from-the-portal.md
  microsoft-community-training/user-management/manage-users/send-announcement-to-the-users.md
  microsoft-community-training/user-management/organization-management.md
  microsoft-community-training/user-management/organize-users/1-create-a-new-group.md
  microsoft-community-training/user-management/organize-users/2-add-a-single-user-to-the-group.md
  microsoft-community-training/user-management/organize-users/3-add-multiple-users-to-the-group.md
  microsoft-community-training/user-management/organize-users/4-setup-automatic-user-enrollment-for-a-group-1.md
  microsoft-community-training/user-management/user-management-overview.md
Labels: do-not-merge, Change sent to author, learning-azure/prod

#298 content management - text updated
  microsoft-community-training/content-management/content-management-overview.md
  microsoft-community-training/content-management/create-content/create-course-category/add-assessments-to-a-course.md
  microsoft-community-training/content-management/create-content/create-course-category/add-feedback-form-for-a-course.md
  microsoft-community-training/content-management/create-content/create-course-category/add-subtitles-or-captions-to-video-content.md
  microsoft-community-training/content-management/create-content/create-course-category/content-marketplace.md
  microsoft-community-training/content-management/create-content/create-course-category/create-a-category.md
  microsoft-community-training/content-management/create-content/create-course-category/create-a-new-course.md
  microsoft-community-training/content-management/create-content/create-course-category/publishing-course.md
  microsoft-community-training/content-management/create-content/create-course-category/upload-content-to-a-course.md
  microsoft-community-training/content-management/create-content/create-learning-path/add-course-to-a-learning-path.md
  microsoft-community-training/content-management/create-content/create-learning-path/create-a-learning-path.md
  microsoft-community-training/content-management/create-content/create-learning-path/publish-a-learning-path-on-the-portal.md
  microsoft-community-training/content-management/manage-content/manage-course-category/add-an-administrator-for-a-course.md
  microsoft-community-training/content-management/manage-content/manage-course-category/change-category-details.md
  microsoft-community-training/content-management/manage-content/manage-course-category/change-course-details.md
  microsoft-community-training/content-management/manage-content/manage-course-category/manage-users-for-a-course.md
  microsoft-community-training/content-management/manage-content/manage-course-category/move-course-content-across-training-instance.md
  microsoft-community-training/content-management/manage-content/manage-learning-path/add-an-administrator-for-a-learning-path.md
  microsoft-community-training/content-management/manage-content/manage-learning-path/change-learning-path-details.md
  microsoft-community-training/content-management/manage-content/manage-learning-path/manage-user-for-a-learning-path.md
Labels: do-not-merge, Change sent to author, learning-azure/prod
