Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2023-03, with the labels that each got.

#244 [METADATA UPDATE] Global metadata/header/navigation changes
  microsoft-community-training/docfx.json
Labels: needs-human-review, do-not-merge, review-team-triage

#245 changes
  microsoft-community-training/docfx.json
Labels: do-not-merge, review-team-triage

#247 Kashyap
  MCT_DB Schema_Mar 2023.pdf
  microsoft-community-training/analytics/custom-reports/database-schema.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/Recommended-settings-for-MCT-Azure-resources.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-multiple-authentications-in-a-single-instance.md
  microsoft-community-training/media/Azure-res4.png
  microsoft-community-training/media/Azure_res1.png
  microsoft-community-training/media/Azure_res2.png
  microsoft-community-training/media/Azure_res3.png
  microsoft-community-training/media/Azure_res5.png
  microsoft-community-training/media/Azure_res6.png
  microsoft-community-training/media/Azure_res7.png
  microsoft-community-training/media/MCT_DB Schema_Mar 2023.pdf
  microsoft-community-training/media/Microsoft Community Training - DB Schema Overview(1).pdf
  microsoft-community-training/media/Smart_group_edit.png
  microsoft-community-training/settings/add-additional-profile-fields-for-user-information.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2023/Whats-new-in-march-2023.md
  microsoft-community-training/whats-new-in-microsoft-community-training/whats-new-in-microsoft-community-training.md
Labels: do-not-merge

#250 dbschemalink
  microsoft-community-training/analytics/custom-reports/database-schema.md
Labels: do-not-merge, Change sent to author, learning-azure/prod

#251 What's new mar23
  microsoft-community-training/TOC.yml
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/Recommended-settings-for-MCT-Azure-resources.md
  microsoft-community-training/media/admin ui localization.png
  microsoft-community-training/media/admin_UI.png
  microsoft-community-training/whats-new-in-microsoft-community-training/2023/Whats-new-in-march-2023.md
  microsoft-community-training/whats-new-in-microsoft-community-training/whats-new-in-microsoft-community-training.md
Labels: do-not-merge

#252 What's new in the March'23
  microsoft-community-training/TOC.yml
  microsoft-community-training/analytics/custom-reports/database-schema.md
  microsoft-community-training/docfx.json
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/Recommended-settings-for-MCT-Azure-resources.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/configure-multiple-authentications-in-a-single-instance.md
  microsoft-community-training/media/Azure-res4.png
  microsoft-community-training/media/Azure_res1.png
  microsoft-community-training/media/Azure_res2.png
  microsoft-community-training/media/Azure_res3.png
  microsoft-community-training/media/Azure_res5.png
  microsoft-community-training/media/Azure_res6.png
  microsoft-community-training/media/Azure_res7.png
  microsoft-community-training/media/MCT_DB Schema_Mar 2023.pdf
  microsoft-community-training/media/Microsoft Community Training - DB Schema Overview(1).pdf
  microsoft-community-training/media/Smart_group_edit.png
  microsoft-community-training/media/admin ui localization.png
  microsoft-community-training/media/admin_UI.png
  microsoft-community-training/settings/add-additional-profile-fields-for-user-information.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2023/Whats-new-in-march-2023.md
  microsoft-community-training/whats-new-in-microsoft-community-training/whats-new-in-microsoft-community-training.md
Labels: do-not-merge

#253 Update Whats-new-in-march-2023.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2023/Whats-new-in-march-2023.md
Labels: do-not-merge, Change sent to author, learning-azure/prod
