Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2023-01, with the labels that each got.

#219 Jan 2023 adhoc changes
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-teams-app-for-your-training-portal.md
  microsoft-community-training/media/doc_3_1.png
  microsoft-community-training/settings/configurations-on-the-training-platform.md
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod

#220 04 Jan
  microsoft-community-training/infrastructure-management/install-your-platform-instance/create-teams-app-for-your-training-portal.md
  microsoft-community-training/media/doc_3_1.png
  microsoft-community-training/settings/configurations-on-the-training-platform.md
Labels: do-not-merge, Change sent to author, learning-azure/prod

#223 AutoScale , Identity configuration error troubleshooting.
  microsoft-community-training/content-management/create-content/create-course-category/content-marketplace.md
  microsoft-community-training/frequently-asked-questions/generate-new-clientsecret-link-to-key-vault.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/scale-up-instance-configuration.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/troubleshooting.md
  microsoft-community-training/media/10JanAuto_1.png
  microsoft-community-training/media/10JanStd.png
  microsoft-community-training/media/10Jan_Disable.png
  microsoft-community-training/media/10Jan_Disable1.png
  microsoft-community-training/media/10Jan_config.png
  microsoft-community-training/media/10Jan_enable.png
  microsoft-community-training/media/10Jan_enable1.png
  microsoft-community-training/media/10Jan_errorconfig.png
  microsoft-community-training/media/10Jan_fa.png
  microsoft-community-training/media/10jan_ADCon.png
  microsoft-community-training/media/10jan_adser.png
  microsoft-community-training/media/AzureADCS.png
  microsoft-community-training/media/AzureADCS1.png
Labels: do-not-merge

#226 Update scale-up-instance-configuration.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/scale-up-instance-configuration.md
Labels: do-not-merge, Change sent to author, learning-azure/prod

#228 Live
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/scale-up-instance-configuration.md
Labels: qualifies-for-auto-merge, do-not-merge

#229 Update whats-new-in-april-2020.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-april-2020.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, learning-azure/prod

#233 Update whats-new-in-february-2020.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-february-2020.md
Labels: do-not-merge, Change sent to author, learning-azure/prod

#234 Offline FAQ
  microsoft-community-training/TOC.yml
  microsoft-community-training/learning-in-offline-mode/frequently-asked-questions.md
  microsoft-community-training/media/offline-sync.png
Labels: do-not-merge

#236 Live
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-february-2020.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, learning-azure/prod
