Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2023-11, with the labels that each got.

#308 Whats-new-section [text-updated]
  microsoft-community-training/content-management/create-content/create-course-category/create-a-category.md
  microsoft-community-training/content-management/create-content/create-course-category/create-a-new-course.md
  microsoft-community-training/content-management/create-content/create-course-category/upload-content-to-a-course.md
  microsoft-community-training/frequently-asked-questions/analytics-reporting.md
  microsoft-community-training/frequently-asked-questions/custom-integration.md
  microsoft-community-training/frequently-asked-questions/faqs-course.md
  microsoft-community-training/frequently-asked-questions/faqs-general.md
  microsoft-community-training/frequently-asked-questions/faqs-installation-and-setup.md
  microsoft-community-training/frequently-asked-questions/faqs-user-management.md
  microsoft-community-training/frequently-asked-questions/generate-new-clientsecret-link-to-key-vault.md
  microsoft-community-training/frequently-asked-questions/portal-branding-customization.md
  microsoft-community-training/frequently-asked-questions/pricing-subscription.md
  microsoft-community-training/frequently-asked-questions/security-and-privacy.md
  microsoft-community-training/frequently-asked-questions/user-roles-groups.md
  microsoft-community-training/frequently-asked-questions/web-mobile-app.md
  microsoft-community-training/settings/configurations-on-the-training-platform.md
  microsoft-community-training/settings/customize-languages-for-the-learners-on-the-platform.md
  microsoft-community-training/settings/customize-the-look-and-feel-of-your-portal.md
  microsoft-community-training/settings/link-to-external-website-on-learner-Homepage.md
  microsoft-community-training/user-management/manage-users/edit-user-profile-on-the-platform.md
  microsoft-community-training/user-management/manage-users/remove-user-from-group.md
  microsoft-community-training/user-management/manage-users/remove-user-from-the-platform.md
  microsoft-community-training/user-management/organization-management.md
  microsoft-community-training/user-management/organize-users/1-create-a-new-group.md
  microsoft-community-training/user-management/organize-users/2-add-a-single-user-to-the-group.md
  microsoft-community-training/user-management/organize-users/3-add-multiple-users-to-the-group.md
  microsoft-community-training/user-management/organize-users/4-setup-automatic-user-enrollment-for-a-group-1.md
  microsoft-community-training/user-management/organize-users/add-a-single-user-to-the-group.md
  microsoft-community-training/user-management/organize-users/add-multiple-users-to-the-group.md
  microsoft-community-training/user-management/organize-users/create-a-new-group.md
  microsoft-community-training/user-management/organize-users/setup-automatic-user-enrollment-for-a-group-1.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-april-2020.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-august-2020.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-december-2020.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-february-2020.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2020/whats-new-in-june-2020.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2021/what-new-in-july-2021.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2021/what-new-in-march-2021.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2021/whats-new-in-october-2021.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-august-2022.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-december-2022.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-february-2022.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2022/whats-new-in-may-2022.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2023/Whats-new-in-Aug-2023.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2023/Whats-new-in-march-2023.md
  microsoft-community-training/whats-new-in-microsoft-community-training/whats-new-in-microsoft-community-training.md
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod

#309 updated TOC and some rogue files
  microsoft-community-training/TOC.yml
  microsoft-community-training/content-management/create-content/create-course-category/content-marketplace.md
  microsoft-community-training/frequently-asked-questions/custom-integration.md
  microsoft-community-training/learner-experience/pwa-app.md
  microsoft-community-training/settings/add-additional-profile-fields-for-user-information.md
  microsoft-community-training/settings/configurations-on-the-training-platform.md
  microsoft-community-training/settings/customize-languages-for-the-learners-on-the-platform.md
  microsoft-community-training/settings/customize-the-certificate-template.md
  microsoft-community-training/settings/enable-course-level-certificate.md
  microsoft-community-training/settings/link-to-external-website-on-learner-Homepage.md
  microsoft-community-training/settings/request-a-new-language.md
  microsoft-community-training/settings/restrict-content-access-to-group-administrators.md
  microsoft-community-training/settings/restrict-portal-access-to-users-outside-your-organization.md
  microsoft-community-training/user-management/manage-users/remove-user-from-the-platform.md
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod

#312 Settings section images updated
  microsoft-community-training/media/Additional Profil Field - Main screen.PNG
  microsoft-community-training/media/Profile Field - name translation.PNG
  microsoft-community-training/media/Profile Field - set validation.PNG
  microsoft-community-training/media/admin_UI.png
  microsoft-community-training/media/certificate selection.png
  microsoft-community-training/media/image(263).png
  microsoft-community-training/media/image(265).png
  microsoft-community-training/media/image(266).png
  microsoft-community-training/media/image(267).png
  microsoft-community-training/media/image(268).png
  microsoft-community-training/media/image(269).png
  microsoft-community-training/media/image(271).png
  microsoft-community-training/media/image(275).png
  microsoft-community-training/media/image(327).png
  microsoft-community-training/media/image(379).png
  microsoft-community-training/media/image(381).png
  microsoft-community-training/media/image(383).png
  microsoft-community-training/media/select certificate .png
  microsoft-community-training/settings/add-additional-profile-fields-for-user-information.md
  microsoft-community-training/settings/configurations-on-the-training-platform.md
  microsoft-community-training/settings/customize-languages-for-the-learners-on-the-platform.md
  microsoft-community-training/settings/customize-the-look-and-feel-of-your-portal.md
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod

#311 Analytics images updated v2
  microsoft-community-training/analytics/in-built-reports/category-view-report.md
  microsoft-community-training/analytics/in-built-reports/course-view-report.md
  microsoft-community-training/analytics/in-built-reports/group-view-report.md
  microsoft-community-training/analytics/in-built-reports/learner-report-card-view.md
  microsoft-community-training/analytics/in-built-reports/overall-summary.md
  microsoft-community-training/media/image(216).png
  microsoft-community-training/media/image(217).png
  microsoft-community-training/media/image(218).png
  microsoft-community-training/media/image(31).png
  microsoft-community-training/media/image(33).png
  microsoft-community-training/media/image(34).png
  microsoft-community-training/media/image(35).png
  microsoft-community-training/media/image(36).png
  microsoft-community-training/media/image(37).png
  microsoft-community-training/media/image(38).png
  microsoft-community-training/media/image(39).png
  microsoft-community-training/media/image(40).png
  microsoft-community-training/media/image(430).png
  microsoft-community-training/media/image(45).png
  microsoft-community-training/media/image(46).png
  microsoft-community-training/media/image(47).png
  microsoft-community-training/media/image(53).png
  microsoft-community-training/media/image(54).png
  microsoft-community-training/media/image(55).png
  microsoft-community-training/media/image(66).png
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod

#314 user-management-content-management-images updated
  microsoft-community-training/media/Add Admin by Org Admin 2.png
  microsoft-community-training/media/Add administrator phone number.png
  microsoft-community-training/media/Add administrator.png
  microsoft-community-training/media/Add rules to Smart Group1.png
  microsoft-community-training/media/Add rules to Smart Group2.png
  microsoft-community-training/media/Add rules to Smart Group3.png
  microsoft-community-training/media/Add rules to Smart Group4a.png
  microsoft-community-training/media/Add single user one.png
  microsoft-community-training/media/Bulk uplod lesson drop down.png
  microsoft-community-training/media/Course Management - Course and Category.png
  microsoft-community-training/media/Delet user from group.png
  microsoft-community-training/media/Delete Category drop-down.png
  microsoft-community-training/media/Delete course drop down.png
  microsoft-community-training/media/Edit course details drop down.png
  microsoft-community-training/media/Enroll User.png
  microsoft-community-training/media/Import CSV icon.png
  microsoft-community-training/media/MCT Complete your profile.png
  microsoft-community-training/media/Manage admin drop down.png
  microsoft-community-training/media/Manage users.png
  microsoft-community-training/media/New Learning Path icon.png
  microsoft-community-training/media/Org Admin addition.png
  microsoft-community-training/media/Publish LP.png
  microsoft-community-training/media/RemoveUserfromGrp(1).png
  microsoft-community-training/media/Track analytics.png
  microsoft-community-training/media/User Management - Add Users - Add Global Admin-border.png
  microsoft-community-training/media/User Management - Organize Users - New Group.png
  microsoft-community-training/media/image(51).png
  microsoft-community-training/media/marketplacesearch.png
Labels: needs-human-review, do-not-merge, review-team-triage

#313 Update faqs-general.md
  microsoft-community-training/frequently-asked-questions/faqs-general.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, learning-azure/prod

#315 replacing terms for quiz/exams
  microsoft-community-training/analytics/in-built-reports/course-view-report.md
  microsoft-community-training/analytics/in-built-reports/group-view-report.md
  microsoft-community-training/content-management/content-management-overview.md
  microsoft-community-training/content-management/create-content/create-course-category/add-assessments-to-a-course.md
  microsoft-community-training/content-management/create-content/create-course-category/create-a-category.md
  microsoft-community-training/content-management/create-content/create-course-category/publishing-course.md
  microsoft-community-training/content-management/create-content/create-course-category/upload-content-to-a-course.md
  microsoft-community-training/content-management/manage-content/manage-course-category/move-course-content-across-training-instance.md
  microsoft-community-training/frequently-asked-questions/analytics-reporting.md
  microsoft-community-training/frequently-asked-questions/custom-integration.md
  microsoft-community-training/frequently-asked-questions/faqs-course.md
  microsoft-community-training/frequently-asked-questions/portal-branding-customization.md
  microsoft-community-training/get-started/microsoft-community-training-overview.md
  microsoft-community-training/get-started/step-by-step-configuration-guide.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/business-continuity-and-disaster-recovery-for-your-platform-instance.md
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/learner-action-events-infrastructure.md
  microsoft-community-training/learner-experience/web-app.md
  microsoft-community-training/whats-new-in-microsoft-community-training/2023/Whats-new-in-Aug-2023.md
Labels: do-not-merge, Change sent to author, learning-azure/prod

#316 learner-experience-images updated
  microsoft-community-training/learner-experience/pwa-app.md
  microsoft-community-training/learner-experience/web-app.md
  microsoft-community-training/media/LearnerLanguage1.png
  microsoft-community-training/media/MCT Complete your profile.png
  microsoft-community-training/media/Profile Field - edit from learner view 0.PNG
  microsoft-community-training/media/Profile Field - edit from learner view 1.PNG
  microsoft-community-training/media/image(163).png
  microsoft-community-training/media/image(173).png
  microsoft-community-training/media/image(181).png
  microsoft-community-training/media/image(182).png
  microsoft-community-training/media/image(186).png
  microsoft-community-training/media/image(188).png
  microsoft-community-training/media/image(189).png
  microsoft-community-training/media/image(414).png
  microsoft-community-training/media/image(415).png
  microsoft-community-training/media/image(434).png
  microsoft-community-training/media/image(435).png
  microsoft-community-training/media/pwa_Ss.png
  microsoft-community-training/media/pwa_Ss_2.png
  microsoft-community-training/media/pwaoffdelete.png
  microsoft-community-training/media/pwaoffhomepage.png
  microsoft-community-training/media/pwaofflang.png
  microsoft-community-training/media/pwaofflogin.png
  microsoft-community-training/media/pwaoffvoureview.png
Labels: do-not-merge, Change sent to author, learning-azure/prod

#317 small updates for some sections
  microsoft-community-training/analytics/analytics-overview.md
  microsoft-community-training/analytics/custom-reports/database-schema.md
  microsoft-community-training/analytics/custom-reports/power-bi-integration.md
  microsoft-community-training/analytics/in-built-reports/category-view-report.md
  microsoft-community-training/analytics/in-built-reports/course-view-report.md
  microsoft-community-training/analytics/in-built-reports/group-view-report.md
  microsoft-community-training/analytics/in-built-reports/learner-report-card-view.md
  microsoft-community-training/analytics/in-built-reports/overall-summary.md
  microsoft-community-training/learner-experience/pwa-app.md
  microsoft-community-training/learner-experience/web-app.md
  microsoft-community-training/learning-in-offline-mode/azure-IOT-edge-device-setup.md
  microsoft-community-training/learning-in-offline-mode/azure-IOT-hub-initial-setup.md
  microsoft-community-training/learning-in-offline-mode/frequently-asked-questions.md
  microsoft-community-training/learning-in-offline-mode/offline-learning-with-microsoft-community-training.md
  microsoft-community-training/media/MCT Complete your profile.png
  microsoft-community-training/media/Profile Field - edit from learner view 2.PNG
  microsoft-community-training/media/pwaofflogin.png
Labels: do-not-merge, Change sent to author, learning-azure/prod, power-bi-embedded/svc

#320 small updates for settings/get-started
  microsoft-community-training/get-started/microsoft-community-training-overview.md
  microsoft-community-training/get-started/step-by-step-configuration-guide.md
  microsoft-community-training/get-started/user-role-and-management-portal-overview.md
  microsoft-community-training/settings/add-additional-profile-fields-for-user-information.md
  microsoft-community-training/settings/configurations-on-the-training-platform.md
  microsoft-community-training/settings/customize-languages-for-the-learners-on-the-platform.md
  microsoft-community-training/settings/customize-the-certificate-template.md
  microsoft-community-training/settings/customize-the-look-and-feel-of-your-portal.md
  microsoft-community-training/settings/enable-course-level-certificate.md
  microsoft-community-training/settings/link-to-external-website-on-learner-Homepage.md
  microsoft-community-training/settings/request-a-new-language.md
  microsoft-community-training/settings/restrict-content-access-to-group-administrators.md
  microsoft-community-training/settings/restrict-portal-access-to-users-outside-your-organization.md
Labels: needs-human-review, do-not-merge, Change sent to author, learning-azure/prod

#334 Adding Reliability Documentation to Live for enabling adding into new azure portal
  microsoft-community-training/TOC.yml
  microsoft-community-training/infrastructure-management/monitor-your-platform-infrastructure/reliability-in-community-training.md
Labels: do-not-merge, Change sent to author, non-product-specific/prod

#336 Removing the Non Profit Setup page
  microsoft-community-training/TOC.yml
  microsoft-community-training/infrastructure-management/install-your-platform-instance/detailed-step-by-step-installation-guide.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/setup-platform-instance-on-azure-subscription-for-nonprofits.md
Labels: do-not-merge, Change sent to author, learning-azure/prod
