Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2024-03, with the labels that each got.

#361 Phone Auth
  microsoft-community-training/media/Phone_Auth_Migration_Files/README.md
  microsoft-community-training/media/Phone_Auth_Migration_Files/SignUpOrSignInWithPhone.xml
  microsoft-community-training/media/Phone_Auth_Migration_Files/SignUpOrSigninWithPhoneOrSocialAccount.xml
  microsoft-community-training/media/Phone_Auth_Migration_Files/TrustFrameworkBase.xml
  microsoft-community-training/media/Phone_Auth_Migration_Files/TrustFrameworkExtensions.xml
Labels: do-not-merge

#362 Live to Main Merge for reconciliation
  microsoft-community-training/TOC.yml
Labels: do-not-merge, review-team-triage

#364 Updated ReadME instructions for Phoneauth Native ADB2C Setup
  microsoft-community-training/infrastructure-management/install-your-platform-instance/CloudShell_Guidance.jpg
  microsoft-community-training/media/Phone_Auth_Migration_Files/CloudShell_Guidance.jpg
  microsoft-community-training/media/Phone_Auth_Migration_Files/README.md
  microsoft-community-training/media/Phone_Auth_Migration_Files/setup.ps1
Labels: do-not-merge, review-team-triage

#365 Updated ReadME instructions for Phoneauth Native ADB2C Setup
  microsoft-community-training/infrastructure-management/install-your-platform-instance/CloudShell_Guidance.jpg
  microsoft-community-training/media/Phone_Auth_Migration_Files/CloudShell_Guidance.jpg
  microsoft-community-training/media/Phone_Auth_Migration_Files/README.md
  microsoft-community-training/media/Phone_Auth_Migration_Files/setup.ps1
Labels: do-not-merge, review-team-triage

#366 Updated the script path in ReadME for PhoneauthMigrationFiles
  microsoft-community-training/media/Phone_Auth_Migration_Files/README.md
Labels: do-not-merge

#367 Updated the script path in ReadME for PhoneauthMigrationFiles
  microsoft-community-training/media/Phone_Auth_Migration_Files/README.md
Labels: do-not-merge, review-team-triage

#368 Updated the link to Teams installation steps
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/customize-the-name-and-icon-of-the-training-tab-in-ms-teams.md
Labels: do-not-merge, Change sent to author, azure/svc

#369 Updated the link to Teams Installation file in the Change Logo section
  microsoft-community-training/infrastructure-management/configure-your-platform-infrastructure/customize-the-name-and-icon-of-the-training-tab-in-ms-teams.md
Labels: do-not-merge, Change sent to author, azure/svc

#370 Added the Public Preview to GA Documentation
  microsoft-community-training/get-started/GA Version Migration/Enable-API-using-S2S-for-GA.md
  microsoft-community-training/get-started/GA Version Migration/Enabling-Data-Export.md
  microsoft-community-training/get-started/GA Version Migration/Learner-Events.md
  microsoft-community-training/get-started/GA Version Migration/Migrating-from-Public-Preview-to-GA-Version.md
  microsoft-community-training/get-started/GA Version Migration/Migration-FAQs.md
  microsoft-community-training/get-started/GA Version Migration/Rest-API-Documentation.md
  microsoft-community-training/media/GA_Migration/API_Documentation/Setp7.jpg
  microsoft-community-training/media/GA_Migration/EVents_Migration/Step_2.png
  microsoft-community-training/media/GA_Migration/EVents_Migration/Step_4.png
  microsoft-community-training/media/GA_Migration/EVents_Migration/Step_5.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Azure Portal Homepage.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Create_Button_SQL_Server.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Create_SQL_Server.jpg
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Final_Create.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Firewall_Settings.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Post_Deployment_SQL_Details.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/REsource_Search_Box.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Review_Create.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/SQL_Server_Basic_Information.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Search_Results_SQL_Server.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Wait_Deployment.png
  microsoft-community-training/media/GA_Migration/S2S_forGA/AppID_PIc3.png
  microsoft-community-training/media/GA_Migration/S2S_forGA/Identity_Pic4.png
  microsoft-community-training/media/GA_Migration/S2S_forGA/Overview_Pic2.png
  microsoft-community-training/media/GA_Migration/S2S_forGA/Register_Service_Save_Pic1.png
Labels: do-not-merge

#371 Added the Public Preview to GA Migration Documentation
  microsoft-community-training/get-started/GA Version Migration/Enable-API-using-S2S-for-GA.md
  microsoft-community-training/get-started/GA Version Migration/Enabling-Data-Export.md
  microsoft-community-training/get-started/GA Version Migration/Learner-Events.md
  microsoft-community-training/get-started/GA Version Migration/Migrating-from-Public-Preview-to-GA-Version.md
  microsoft-community-training/get-started/GA Version Migration/Migration-FAQs.md
  microsoft-community-training/get-started/GA Version Migration/Rest-API-Documentation.md
  microsoft-community-training/media/GA_Migration/API_Documentation/Setp7.jpg
  microsoft-community-training/media/GA_Migration/EVents_Migration/Step_2.png
  microsoft-community-training/media/GA_Migration/EVents_Migration/Step_4.png
  microsoft-community-training/media/GA_Migration/EVents_Migration/Step_5.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Azure Portal Homepage.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Create_Button_SQL_Server.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Create_SQL_Server.jpg
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Final_Create.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Firewall_Settings.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Post_Deployment_SQL_Details.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/REsource_Search_Box.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Review_Create.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/SQL_Server_Basic_Information.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Search_Results_SQL_Server.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Wait_Deployment.png
  microsoft-community-training/media/GA_Migration/S2S_forGA/AppID_PIc3.png
  microsoft-community-training/media/GA_Migration/S2S_forGA/Identity_Pic4.png
  microsoft-community-training/media/GA_Migration/S2S_forGA/Overview_Pic2.png
  microsoft-community-training/media/GA_Migration/S2S_forGA/Register_Service_Save_Pic1.png
Labels: do-not-merge

#372 Public Preview to GA Migration Documentation (NOT PUBLIC YET)
  microsoft-community-training/get-started/GA Version Migration/Enable-API-using-S2S-for-GA.md
  microsoft-community-training/get-started/GA Version Migration/Enabling-Data-Export.md
  microsoft-community-training/get-started/GA Version Migration/Learner-Events.md
  microsoft-community-training/get-started/GA Version Migration/Migrating-from-Public-Preview-to-GA-Version.md
  microsoft-community-training/get-started/GA Version Migration/Migration-FAQs.md
  microsoft-community-training/get-started/GA Version Migration/Rest-API-Documentation.md
  microsoft-community-training/media/GA_Migration/API_Documentation/Setp7.jpg
  microsoft-community-training/media/GA_Migration/EVents_Migration/Step_2.png
  microsoft-community-training/media/GA_Migration/EVents_Migration/Step_4.png
  microsoft-community-training/media/GA_Migration/EVents_Migration/Step_5.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Azure Portal Homepage.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Create_Button_SQL_Server.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Create_SQL_Server.jpg
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Final_Create.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Firewall_Settings.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Post_Deployment_SQL_Details.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/REsource_Search_Box.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Review_Create.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/SQL_Server_Basic_Information.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Search_Results_SQL_Server.png
  microsoft-community-training/media/GA_Migration/Enabling_Data_Export_Pictures/Wait_Deployment.png
  microsoft-community-training/media/GA_Migration/S2S_forGA/AppID_PIc3.png
  microsoft-community-training/media/GA_Migration/S2S_forGA/Identity_Pic4.png
  microsoft-community-training/media/GA_Migration/S2S_forGA/Overview_Pic2.png
  microsoft-community-training/media/GA_Migration/S2S_forGA/Register_Service_Save_Pic1.png
Labels: do-not-merge, Change sent to author, azure/svc

#373 PUblic Preview to GA Migration Documentation
  microsoft-community-training/get-started/GA-Version-Migration/Enable-API-using-S2S-for-GA.md
  microsoft-community-training/get-started/GA-Version-Migration/Enabling-Data-Export.md
  microsoft-community-training/get-started/GA-Version-Migration/Learner-Events.md
  microsoft-community-training/get-started/GA-Version-Migration/Migrating-from-Public-Preview-to-GA-Version.md
  microsoft-community-training/get-started/GA-Version-Migration/Migration-FAQs.md
  microsoft-community-training/get-started/GA-Version-Migration/Rest-API-Documentation.md
Labels: do-not-merge

#375 updated formatting
  microsoft-community-training/get-started/GA-Version-Migration/Enabling-Data-Export.md
  microsoft-community-training/get-started/GA-Version-Migration/Migrating-from-Public-Preview-to-GA-Version.md
  microsoft-community-training/get-started/GA-Version-Migration/Rest-API-Documentation.md
Labels: do-not-merge

#379 Minor Edits to the documentation format. (NOT PUBLIC)
  microsoft-community-training/get-started/GA-Version-Migration/Enabling-Data-Export.md
  microsoft-community-training/get-started/GA-Version-Migration/Migrating-from-Public-Preview-to-GA-Version.md
  microsoft-community-training/get-started/GA-Version-Migration/Migration-FAQs.md
  microsoft-community-training/get-started/GA-Version-Migration/Rest-API-Documentation.md
Labels: do-not-merge, Change sent to author, azure/svc

#380 Minor Edits to GA Migration Document (NOT PUBLIC YET)
  microsoft-community-training/get-started/GA-Version-Migration/Enabling-Data-Export.md
  microsoft-community-training/get-started/GA-Version-Migration/Migrating-from-Public-Preview-to-GA-Version.md
  microsoft-community-training/get-started/GA-Version-Migration/Migration-FAQs.md
  microsoft-community-training/get-started/GA-Version-Migration/Rest-API-Documentation.md
Labels: do-not-merge, Change sent to author, azure/svc
