Repository MicrosoftDocs/microsoft-community-training, pull requests merged in 2024-04, with the labels that each got.

#382 Minor Formatting changes
  microsoft-community-training/get-started/GA-Version-Migration/Enable-API-using-S2S-for-GA.md
  microsoft-community-training/get-started/GA-Version-Migration/Enabling-Data-Export.md
  microsoft-community-training/get-started/GA-Version-Migration/Migrating-from-Public-Preview-to-GA-Version.md
  microsoft-community-training/get-started/GA-Version-Migration/Migration-FAQs.md
Labels: do-not-merge, Change sent to author, azure/svc

#383 Minor Formatting Changes
  microsoft-community-training/get-started/GA-Version-Migration/Enable-API-using-S2S-for-GA.md
  microsoft-community-training/get-started/GA-Version-Migration/Enabling-Data-Export.md
  microsoft-community-training/get-started/GA-Version-Migration/Migrating-from-Public-Preview-to-GA-Version.md
  microsoft-community-training/get-started/GA-Version-Migration/Migration-FAQs.md
Labels: do-not-merge, Change sent to author, azure/svc

#385 Create ADB2C.md
  microsoft-community-training/infrastructure-management/install-your-platform-instance/ADB2C.md
Labels: do-not-merge

#386 Updated PhoneAuth Migration Documentation
  microsoft-community-training/media/Phone_Auth_Migration_Files/ADB2C.md
  microsoft-community-training/media/Phone_Auth_Migration_Files/IdentityMigration.csv
  microsoft-community-training/media/Phone_Auth_Migration_Files/Identity_Migration_Userguide
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Admin_Driven_Migration/CSV UPload Screen.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Admin_Driven_Migration/Notifications.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Final_Message.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Input_Mobile_Number.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Max_OPT_Tries.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Migration_1_Mobile_Input.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Migration_Failure.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Mobile_Landing_Page.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Mobile_Number_Not_Match.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/OTP_Screen.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Post_Migration_Screen.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Pre_message_Landing_Page.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/SIgnUP_Page.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Sign_in_Page.png
  microsoft-community-training/media/cliendIDB2C.png
Labels: do-not-merge, review-team-triage

#387 Updated PhoneAuth Migration Documentation
  microsoft-community-training/media/Phone_Auth_Migration_Files/ADB2C.md
  microsoft-community-training/media/Phone_Auth_Migration_Files/IdentityMigration.csv
  microsoft-community-training/media/Phone_Auth_Migration_Files/Identity_Migration_Userguide
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Admin_Driven_Migration/CSV UPload Screen.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Admin_Driven_Migration/Notifications.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Final_Message.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Input_Mobile_Number.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Max_OPT_Tries.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Migration_1_Mobile_Input.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Migration_Failure.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Mobile_Landing_Page.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Mobile_Number_Not_Match.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/OTP_Screen.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Post_Migration_Screen.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Migration_Screenshots/Learner_Driven_Migration/Pre_message_Landing_Page.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/SIgnUP_Page.png
  microsoft-community-training/media/Phone_Auth_Migration_Files/Sign_in_Page.png
  microsoft-community-training/media/cliendIDB2C.png
Labels: do-not-merge, review-team-triage

#388 minor edits
  microsoft-community-training/get-started/GA-Version-Migration/Rest-API-Documentation.md
  microsoft-community-training/media/Phone_Auth_Migration_Files/ADB2C.md
  microsoft-community-training/media/Phone_Auth_Migration_Files/Identity_Migration_Userguide.md
Labels: do-not-merge

#389 Minor Edits
  microsoft-community-training/get-started/GA-Version-Migration/Rest-API-Documentation.md
  microsoft-community-training/media/Phone_Auth_Migration_Files/ADB2C.md
  microsoft-community-training/media/Phone_Auth_Migration_Files/Identity_Migration_Userguide.md
Labels: do-not-merge

#390 Added summary for the document headers
  microsoft-community-training/media/Phone_Auth_Migration_Files/ADB2C.md
  microsoft-community-training/media/Phone_Auth_Migration_Files/Identity_Migration_Userguide.md
Labels: do-not-merge, Change sent to author, azure/svc

#391 Adding the summary ad headers for the files
  microsoft-community-training/media/Phone_Auth_Migration_Files/ADB2C.md
  microsoft-community-training/media/Phone_Auth_Migration_Files/Identity_Migration_Userguide.md
Labels: do-not-merge, Change sent to author, azure/svc
